### ISSUE TITLE
Shimadzu file conversion to .mzML: wrong TIC time array

### ISSUE THREAD

**Issue by egauthierphy** [ProteoWizard/pwiz#1070]
I'm using the C# bindings to load a Shimadzu data file (coming from a 8060) containing scan data (TIC chromatogram + multiple spectras). I'm able to reproduce the problem with SeeMS and MSConvert so I don't think it is specific to the bindings DLL.

Here is the data file: [https://we.tl/t-WjpCHA0Mf3](https://we.tl/t-WjpCHA0Mf3)

Here is what SeeMS loads:

![snap0765](https://user-images.githubusercontent.com/36052122/81862072-2b467880-9537-11ea-8256-222e99cd017e.png)

The actual runtime is 11 minutes (660 seconds). The spectras scan time are correctly reported, but the top TIC chromatogram is not. The time array doesn't contains seconds but tenths of seconds (0 to 66). The resulting mzML as converted by MSConvert also lists the time data array as seconds.

I've processed MRM scans without problems. Is this only related to Scan data?

**Comment by chambm** [comment]
Fixed by https://github.com/ProteoWizard/pwiz/pull/1071 - thanks for the report and test data.
