### ISSUE TITLE
C# bindings: crash when accessing a chromatogram product or precursor

### ISSUE THREAD

**Issue by egauthierphy** [ProteoWizard/pwiz#1072]
I'm trying to get information from the precursor and product ion from a Shimadzu MRM data file. However as soon as I get hold of the precursor object the program crashes at exit. Here is the data converted to mzML:

[https://we.tl/t-VwFlV7CAM1](https://we.tl/t-VwFlV7CAM1)

Here is a minimal example of my code (with latest pw 3.0.20135, compiled against .Net 4.8 with VS 2019):

```csharp
using System;
using pwiz.CLI.msdata;

namespace TestCVParamCrash
{
    class Program
    {
        static void Main(string[] args)
        {
            var msFile = new MSDataFile(@"E:\ConvertedMSDataFile.mzML");

            for (int i = 0; i < msFile.run.chromatogramList.size(); i++)
            {
                var chromatogram = msFile.run.chromatogramList.chromatogram(i, true);
                var precursor = chromatogram.precursor;
                
                bool isPrecursorEmpty = precursor.empty();
                Console.WriteLine($"IsPrecursorEmpty: {isPrecursorEmpty}");
            }
            Console.ReadLine();
        }
    }
}
```

When native code debugging is enabled the call stack shows:

![snap0775](https://user-images.githubusercontent.com/36052122/82077390-5357e800-96ad-11ea-9a96-713222b8d3e2.png)

... leading me to believe the crash happens when the precursor object gets disposed by the GC. You can accelerate the crash if you enclose the precursor calls inside a using statement. It also happens with the product object.

On the same subject but related to Skyline, if I remove the product and precursor from the .mzML Skyline is still able to integrate the file correctly, meaning that Skyline must parse the ID of the chromatogram to identify them. Is there a reason to do this rather than using the product and precursor objects?

**Comment by chambm** [comment]
Fixed in #1081
