### ISSUE TITLE
Skyline: Shimadzu data file not loading

### ISSUE THREAD

**Issue by egauthierphy** [ProteoWizard/pwiz#1102]
I'm encoutering a problem when loading a specific MRM Shimadzu data file inside Skyline 20.1.0.76. The error is:

> Failed importing results file 'E:\Shimadzu Joe\20200601002_Repro_Cocaine_Hexane_003.lcd'.
> The sample 20200601002_Repro_Cocaine_Hexane_003 contains no usable data.

Here is the Skyline method: [https://we.tl/t-FkRKfiX8sU](https://we.tl/t-FkRKfiX8sU)
Here is the problematic data file: [https://we.tl/t-ajSzyRsyEb](https://we.tl/t-ajSzyRsyEb)

Here is another data file from the same MS but different MS method that loads correctly with the same Skyline method (no error given): [https://we.tl/t-fWQhjyfXMu](https://we.tl/t-fWQhjyfXMu)

**Comment by chambm** [comment]
@bspratt tracked this down to a Skyline issue with [files with very few chromatograms](https://github.com/ProteoWizard/pwiz/pull/1109).
