### ISSUE TITLE
"[IO::HandlerBinaryDataArray] Unknown binary data type." when loading mzML file

### ISSUE THREAD

**Issue by luuulu** [ProteoWizard/pwiz#1133]
I am trying to use the [MSnbase R module](http://lgatto.github.io/MSnbase/) to analyze an MRM dataset, however I obtain an error when loading the mzML file (converted with default settings from a Sciex wiff file using MSConvert). 
I already opened an issue at MSnbase (https://github.com/lgatto/MSnbase/issues/517), however since the error message results from the pwiz library that MSnbase uses to load the file, I thought it's better to open an issue here.

The error I obtain is: `Error in pwizModule$open(filename): [IO::HandlerBinaryDataArray] Unknown binary data type.`

I attached the mzML file: [DataBlank-Test_Blank.mzML.zip](https://github.com/ProteoWizard/pwiz/files/4853963/DataBlank-Test_Blank.mzML.zip)

What could be the cause for this error?

**Comment by chambm** [comment]
Replied at MSnbase repo.
