### ISSUE TITLE
Conversion Failure for mixed orbitrap (MS1) / linear ion trap (MS2) HCD Thermo ID-X

### ISSUE THREAD

**Issue by PMSeitzer** [ProteoWizard/pwiz#1160]
proteowizard version:
`Version: 3.0.20034-d7e41e31f (developer build)`

To reproduce:
generate a file on Thermo ID-X, with the following settings:

MS1: orbitrap
MS2: linear ion trap with HCD fragmentation
this also does MS1 SIM scans.

see screenshot:

![Proteowizard_error](https://user-images.githubusercontent.com/1757701/88721580-82da9600-d0db-11ea-929d-9c143fb50d55.png)

Please inquire data transfer.  If anyone has any ideas, I am happy to take this issue on.

**Comment by PMSeitzer** [comment]
a likely related error message is produced when running with

MS1 orbitrap
MS2 ion trap with CID fragmentation (instead of HCD as in above comment):

![MS2_CID_error](https://user-images.githubusercontent.com/1757701/88721998-abfb2680-d0db-11ea-8552-613a0a9e694e.png)

A run of only the MS2 linear ion trap with CID fragmentation (no MS1) converts successfully.
A run of only the MS2 linear ion trap with HCD fragmentation (no MS1) does not complete successfully.

**Comment by chambm** [comment]
Thanks for the report. Please share one of the problematic files for us to fix. Definitely seems like a bug.

**Comment by PMSeitzer** [comment]
Thanks @chambm, Here is a link to two files that produced slightly different errors, with descriptions:

https://drive.google.com/drive/folders/1tpD5XgcUdi74YbABKXWf3HN99uTRwyMr?usp=sharing

**Comment by chambm** [comment]
What version of pwiz are you using? I have to use the `--ignoreUnknownInstrumentError` to get it to convert at all, and then the "no matching instrument configuration" is more of a warning than an error. Nevertheless this ID-X instrument needs to be added so a fix is required.

**Comment by PMSeitzer** [comment]
Hi Matt,

Here is the proteowizard version information:
![proteowizard_version](https://user-images.githubusercontent.com/1757701/88954981-18973200-d250-11ea-9406-ab00ed7d1d15.png)

I tried to convert the file using the `--ignoreUnknownInstrumentError` flag. However, the conversion was unsuccessful (see screenshot):

![ignoreUnknownInstrumentError](https://user-images.githubusercontent.com/1757701/88955014-25b42100-d250-11ea-9ccb-66fa0e095f26.png)

**Comment by chambm** [comment]
Can you try the current version? I get:
![image](https://user-images.githubusercontent.com/5011937/88960352-5eb0bd80-d271-11ea-9427-031901b98bb4.png)

**Comment by chambm** [comment]
Fixed in https://github.com/ProteoWizard/pwiz/pull/1161 (new instruments added; Orbitrap ID-X required a CV update)

**Comment by PMSeitzer** [comment]
Thanks @chambm, I can confirm that the new version works when I use the `--ignoreUnknownInstrumentError` flag.
