### ISSUE TITLE
All pseudo-ms/ms spectra bundled into a single file irregardless of the quality

### ISSUE THREAD

**Issue by MarcIsak** [ProteoWizard/pwiz#1212]
Hi, 

I really like the DIA-Umpire signal extraction feature that has been added to MSConvert. But a difference when  running this feature in MSConvert, as compared to DIA-Umpire,  is that all pseudo-ms/ms spectra from a DIA-file are added together  into a single spectral file, irregardless of the spectral quality. 

However, in DIA-Umpire, the pseudo-ms/ms spectra are divided into three spectral files depending on the quality. The first spectral file contains only pseudo-ms/ms spectra derived from precursors where more than two isotopic peaks were detected. The second file, where only two isotopic peaks were detected for the corresponding precursor ions. The third file has pseudo-ms/ms spectra resulting from precursors where no isotopic peak was detected. This info can be found in the DIA-Umpire manual. 

I just wonder if it would be possible to add the possibility to split the files depending on the quality in MSConvert? Maybe I am asking for too much ;). 

Best,

Marc

**Comment by chambm** [comment]
The command-line msconvert.exe has an option to output the separate quality files, but it's not in the GUI. I'm not a big fan of the separate quality outputs, I feel that should be up to the search engine to sort out scoring for. The same applies for terminal specificity, charge state, hydrophobicity, etc. I think the unified output keeps track of which quality category it's in with a userParam IIRC. (If not it easily could)
