### ISSUE TITLE
how did you create the small.RAW?

### ISSUE THREAD

**Issue by 47Lies** [ProteoWizard/pwiz#1299]
Hi,

More like a question than a issue, but i wanted to know how did you create the small.RAW and if it was possible to use msconvert to extract a single spectrum from an existing .RAW file and keep it in .RAW format?

**Comment by chambm** [comment]
`small.raw` is a real acquired RAW file that was configured with a very short method (0.5 min). It is possible to extract a single spectrum as a RAW file but you lose the file-level metadata in the process. See `FT-HCD-MSX.raw` (in pwiz\data\vendor_readers\Thermo) as an example.

![image](https://user-images.githubusercontent.com/5011937/97452962-aa741100-190b-11eb-8b93-6113eef341cc.png)
