### ISSUE TITLE
Can not load shimadzu lcd file

### ISSUE THREAD

**Issue by rrrrrrr1** [ProteoWizard/pwiz#1333]
I can not open or convert this lcd file, please someone help!

![error image](https://user-images.githubusercontent.com/28670521/100495952-c96ff800-3182-11eb-9bfd-84e1b347e182.png)
[LOAD ERROR LCD file.zip](https://github.com/ProteoWizard/pwiz/files/5610170/LOAD.ERROR.LCD.file.zip)

**Comment by chambm** [comment]
Is it IT-TOF? That's not supported, only QTOF and QQQ.
