### ISSUE TITLE
Different mzML result with different versions

### ISSUE THREAD

**Issue by o-t** [ProteoWizard/pwiz#1583]
Hi,

I used to run msconvert with the Windows GUI, but recently I managed to install the Linux Docker version. I wanted to install the same version as the GUI I have been using (v3.0.20248), but couldn't find it on the Docker repo, so the newest version (v3.0.20287) was installed instead.

When I compared the mzML created by the 2 versions (from the same Thermo .raw file with the same arguments), I found there are quite a few differences. For all the spectra, the `defaultArrayLength`, `binaryDataArray encodedLength`, and `binary` are different. For some of the spectra, the  `cvParam` is in `64-bit float` in the mzML generated by the GUI, but `32-bit float` in the output by the Docker version.

Also, all the lines in `indexList` are different. For example, `<offset idRef="controllerType=0 controllerNumber=1 scan=1">5328</offset>` in GUI but `<offset idRef="controllerType=0 controllerNumber=1 scan=1">5259</offset>` in Docker. The `offset` and `indexListOffset` towards the end of the mzML files are also different.

I am worried that these differences will generate different results during database searching, protein quantification, etc. What would be causing these differences and what do they mean? Thanks!

**Comment by o-t** [comment]
My settings when using the GUI:
![image](https://user-images.githubusercontent.com/54391198/117643862-73848f00-b1bb-11eb-8e1b-ffabd0e2f515.png)

My Docker command-line arguments:
`msconvert /data/*.raw --zlib -o /data/ --filter "peakPicking true 1-" --filter "titleMaker <RunId>.<ScanNumber>.<ScanNumber>.<ChargeState> File: '<SourcePath>'. NativeID: '<Id>'"`

**Comment by o-t** [comment]
The `defaultArrayLength` difference is not the same for all spectra. For example, 1 spectrum has difference like this: `<spectrum index="8" id="controllerType=0 controllerNumber=1 scan=9" defaultArrayLength="31">` in GUI vs `<spectrum index="8" id="controllerType=0 controllerNumber=1 scan=9" defaultArrayLength="34">` in Docker.
Another spectrum difference is like this: `<spectrum index="10" id="controllerType=0 controllerNumber=1 scan=11" defaultArrayLength="46">` in GUI vs `<spectrum index="10" id="controllerType=0 controllerNumber=1 scan=11" defaultArrayLength="47">`

**Comment by chambm** [comment]
Ideally there shouldn't be any difference. I'm 99% sure this difference is due to a change in including "exception" peaks from RAW files. The Docker 20287 release was made right after I committed the change that turned on those peaks. So your Docker files from 20287 would have those peaks, and your MSConvertGUI files from 20248 files would not. To be sure, install a newer MSConvertGUI on Windows and compare again.

**Comment by o-t** [comment]
Thanks Matt. Let me try that and let you know how that goes

**Comment by o-t** [comment]
Results from the current version MSConvertGUI (release 21132) andD ocker 20287 release indeed have the same `defaultArrayLength`. Thanks for the clarification!

The `binaryDataArray` still have different `encodedLength` though (release 21132 is always longer), and all lines in the `indexList` are again different. Are these significant? Thanks again!
