### ISSUE TITLE
(Missing) Installation instructions for building from source on Linux

### ISSUE THREAD

**Issue by stephanmg** [ProteoWizard/pwiz#1622]
Dear all,

hope this finds you well, but I struggle to find information on how to build `pwiz` from source on Linux. 

Should one just look in the `.travis.yml` for hints or am I missing some resources made available elsewhere?

Stephan

**Comment by chambm** [comment]
https://github.com/ProteoWizard/pwiz/blob/master/BUILDING

Note that vendor file conversion is only available with Windows builds (which can also be run on Linux via the Docker/Wine container).
