### ISSUE TITLE
msconvert yields empty files on windows and linux

### ISSUE THREAD

**Issue by jaanli** [ProteoWizard/pwiz#1804]
On Ubuntu 20.04 running on WSL2:

```
export LC_ALL=C
msconvert --mgf  1\ V443\ +22,5\ pos_080419_Recal.mzML
```
The input mzML and output mgf from msconvert are attached:

[1 V443 +22,5 pos_080419_Recal.zip](https://github.com/ProteoWizard/pwiz/files/7370087/1.V443.%2B22.5.pos_080419_Recal.zip)

I also ran this command on Windows with the command line version of msconvert, and with the Windows GUI for ProteoWizard, and it yielded the same results. 

What am I doing wrong? Thanks so much!

**Comment by nickshulman** [comment]
Your mzML file only contains MS1 spectra.

The MGF file format only supports MS2 spectra.

When an MGF file has no spectra in it, the MGF file will be zero bytes long.
-- Nick
