### ISSUE TITLE
Is there a way to get Absorbance data from .WIFF file from SCIEX QQQ 6500 Instrument

### ISSUE THREAD

**Issue by weiran-wang** [ProteoWizard/pwiz#1872]
Hi, thank you for this amazing tools. I'm working on converting some LCMS data from a QTRAP 6500 by using the latest MSConvert. But is there a way to include absorbance data (like Total Wavelength Chromatogram (TWC)) in the exported TXT (or other clear txt format) files? 
Thank you!

**Comment by chambm** [comment]
Can you share the WIFF file? I don't think I've ever seen UV data in a WIFF so I don't know how to pick it out programmatically. We already support pressure and flow rate chromatograms from WIFF.

**Comment by weiran-wang** [comment]
I can definitely share one wiff and wiffscan file here, is there a good way to share these files with you?

**Comment by weiran-wang** [comment]
Besides we can definitely view the absorbance data in Analyst and SciOS.

**Comment by chambm** [comment]
How big are the files? Send me an email (view my profile) and I'll send you a link to upload to.

**Comment by weiran-wang** [comment]
Thank you Matt, it's about 15 MB

**Comment by chambm** [comment]
You can zip them and attach to this issue.

**Comment by weiran-wang** [comment]
[Mass Data Wiff.zip](https://github.com/ProteoWizard/pwiz/files/7644153/Mass.Data.Wiff.zip)

**Comment by weiran-wang** [comment]
I chose a smaller one, and this should contains the absorbance data.

**Comment by chambm** [comment]
It seems there are 2 operating modes: signal and spectrum. The file you attached is in spectrum mode. With no specific wavelengths to target, it seems I can only put a TWC, or output all the EMR spectra? Do you have a signal mode file?

**Comment by weiran-wang** [comment]
No we don't have a signal mode data. And I don't think there is no such mode in the instrument. TWC should stands for Total Wavelength Chromatogram, I think this is what I saw from Analyst.

**Comment by chambm** [comment]
Is that useful for analysis, or just QC? I would think you would want to look at specific wavelengths for doing any analysis. (I know almost nothing about UV-based analysis)

**Comment by weiran-wang** [comment]
I would say yes, UV or TWC also tells you you have something flow through the system at that time. In our case we just want to see if we are missing anything in this sample. But some time, say you are not super sure about what's in this sample, you definitely wants to check the absorbance data. And sometimes you will see: hey I have a absorbance peak here at 2 min, but I cannot see that peak from my TIC/MS figure, what could happen?

**Comment by weiran-wang** [comment]
To add that Absorbance and or TWC should be a very important data collected from a LCMS run.

**Comment by chambm** [comment]
Thanks, I will add TWC when I get a chance and then close this issue.

**Comment by weiran-wang** [comment]
Thank you!
