### ISSUE TITLE
Cannot find Quameter.exe on Proteowizard windows install

### ISSUE THREAD

**Issue by nattzy94** [ProteoWizard/pwiz#1948]
Hi,

I am trying to run Quameter from the Bumbershoot project to get my information about my `raw` files. I first tried to do this on a linux installation of proteowizard by installing via conda. However, I run into vendor format issues.

I then tried this on a windows machine on AWS. After downloading proteowizard from the sourceforge page, I installed the program and located the folder containing the proteowizard `.exe` files and I can find all the software files such as `msconvert.exe`. However, there is no file for `Quameter.exe` as far as I can tell. I've attached a screenshot of the directory here:

<img width="1280" alt="Screen Shot 2022-01-16 at 10 45 21 PM" src="https://user-images.githubusercontent.com/48880365/149665114-7a325826-c575-4953-93a9-9d6999b85404.png">

Any one knows to get Quameter working on Windows?

**Comment by chambm** [comment]
The Bumbershoot tools are a separate download option on the download page:
![image](https://user-images.githubusercontent.com/5011937/149815573-513f5cef-cb5e-446b-8b7a-a759323238e5.png)
