### ISSUE TITLE
pasefMGF loss of precursor intensity? 

### ISSUE THREAD

**Issue by orsburn** [ProteoWizard/pwiz#1949]
Hi ProteoWizard!
When I make an MGF using the pasefMGF defaults using the MSConvert WindowsGUI I don't seem to get a precursor intensity. Is this just a case of the PEPMASS precursor mass and intensity not being separated? 
![image](https://user-images.githubusercontent.com/39571544/149670235-95635604-2329-4eb2-b165-095a29f4e302.png)
Is this something I can fix on my end? 
Thanks!

**Comment by chambm** [comment]
Answered on mailing list.
