### ISSUE TITLE
How to keep the value of collision energy

### ISSUE THREAD

**Issue by MuyaoXi9271** [ProteoWizard/pwiz#2087]
Hi expert,

I would like to consult how to set parameters to keep the values of collision energy of MS2 DDA data after transferring into the format of .mzml. I have tried many settings, ending up with zero for collision energy. I appreciate any help very much.

Bests,
Muyao

**Comment by chambm** [comment]
By MS2 DDA data do you mean the .ms2 format?

**Comment by MuyaoXi9271** [comment]
> By MS2 DDA data do you mean the .ms2 format?

Not really. The format of the raw file is .d and I would like to transfer raw data into the format of .mzml or .mgf. The issue is that I am not able to keep the value of collision energy by adjusting the parameters after transformation.

Bests,
Muyao

**Comment by chambm** [comment]
There are at least 5 ".d" formats: Bruker BAF, Bruker TDF, Agilent/Bruker YEP, Agilent MassHunter, and Agilent Chemstation. Each one has a different API which may or may not support extracting collision energy. Which format is your data?

**Comment by MuyaoXi9271** [comment]
The file is exported from Bruker tims-tof and I check the subfolder where there is a file called analysis.baf. Therefore, I guess it should be Bruker BAF.

Does msconvert support extracting collision energy in terms of this type of file?


Bests,
Muyao

**Comment by chambm** [comment]
TimsTOF should be TDF format. You should have an analysis.tdf file in there. I'm not sure what the analysis.baf would be for. You should be getting collision energy for TDF format. So this is DDA PASEF data? If you're not getting collision energy in the precursors I'd like to see the analysis.tdf file.

**Comment by MuyaoXi9271** [comment]
I am not so familiar with whether it is the DDA PASEF data. Could you please guide me on how to check whether it is the DDA PASEF data? The below image shows the contents of the subfolder of the .d file
![image](https://user-images.githubusercontent.com/87710342/166256008-afd500c6-6805-4a03-8534-7219011ba37d.png)

**Comment by chambm** [comment]
Can you zip up and attach the .sqlite file to this post? I'm pretty doubtful that is really from a timsTOF.

**Comment by MuyaoXi9271** [comment]
Sure, I will send it to you personally, regarding GNPS, I would not like to share it in public.

**Comment by MuyaoXi9271** [comment]
Sure, I will send it to you personally, regarding GDPR, I would not like to share it in public.

**Comment by MuyaoXi9271** [comment]
> Can you zip up and attach the .sqlite file to this post? I'm pretty doubtful that is really from a timsTOF.

Hi Matt Chambers,

Did you receive the zip file?

Bests,
Muyao

**Comment by MuyaoXi9271** [comment]
Thanks very much. I am looking forward to hearing good news.

Bests,
Muyao

**Comment by MuyaoXi9271** [comment]
Hi Matt Chambers,

It works and the value of collision energy is available for the positive mode, but they are not available for the negative mode. Do I need to provide some files for you to fix it?

Bests,
Muyao
