### ISSUE TITLE
Where can I find old versions of pwiz

### ISSUE THREAD

**Issue by fcyu** [ProteoWizard/pwiz#2096]
If I would like to download a specific version of pwiz, where can I find it?

Thanks,

Fengchao

**Comment by nickshulman** [comment]
Which version do you need?

I am not sure whether we keep old versions of ProteoWizard around anywhere.
There are a few old versions from 2020 and 2021 here:
https://proteome.gs.washington.edu/~nicksh/ProteowizardInstallers/
-- Nick

**Comment by fcyu** [comment]
Thank you, Nick!
