### ISSUE TITLE
sldout produces incorrect output on post-run sld files that Xcalibur adds json metadata to (patch included)

### ISSUE THREAD

**Issue by zpincus** [ProteoWizard/pwiz#2312]
We have found that while `sldout` works fine to parse `sld` files saved from Thermo Xcalibur before a run begins, `sld` files saved out after a run ends may contain additional metadata.

This consists of an extra string field at the end of at least some records, which causes `sldout` to exit and write `[readString()] String too long?` to stdout (instead of to stderr where one might expect it to go, btw).

The offending code in `sld.cpp` is:
```c++
for (int i=0; i<recordCount; i++)
{
    records.push_back(readRecord(is));
    if (version >= XcaliburVersion_2_0)
        is.seekg(60, ios::cur);
}
```
i.e. read a record, skip 60 bytes (of all zeros), repeat.

For the files that Xcalibur has added extra metadata to, offending records end with 52 bytes of zeros, one string (which if empty is just as 4 bytes of zeros) and then 4 more bytes of zeros. This string is some horrid json along the lines of:
```json
{"$type":"Thermo.Xcalibur.Common.Models.Experiment.Capabilities.SampleExtensionInfo, Thermo.Xcalibur.Common.Models","CapabilityData":{"$type":"System.Collections.Generic.Dictionary`2[[Thermo.Xcalibur.Common.Models.Experiment.Capabilities.CapabilityTypes, Thermo.Xcalibur.Common.Models],[Thermo.Xcalibur.Common.Models.Experiment.Capabilities.Data.BaseCapabilityData, Thermo.Xcalibur.Common.Models]], mscorlib","ReInject":{"$type":"Thermo.Xcalibur.Common.Models.Experiment.Capabilities.Data.ReInjectData, Thermo.Xcalibur.Common.Models","Id":"00000000-0000-0000-0000-000000000000","OriginalRawFileNameWithoutExtension":"the_original_file_name_would_go_here","DisplayRowNumber":1,"DisplayLabel":0}}}
```

The following will properly parse both the original `sld` files and those with such json strings embedded (just throwing those strings away; obviously they could also be added):
```c++
for (int i=0; i<recordCount; i++)
{
    records.push_back(readRecord(is));
    if (version >= XcaliburVersion_2_0)
    {
        is.seekg(52, ios::cur);
        readString(is);
        is.seekg(4, ios::cur);
    }
}
```

Though I wonder if those 52 bytes of zeros are themselves also just empty reserved fields in which Xcalibur might write other things in the future? So maybe to be safe the loop should do 15 `readString`s (which each consume 4 bytes to check the size of the string that is to be read), or 14 `readString`s followed by one unconditional skip of 4 bytes (if it is expected that records will always end with four zero bytes).

FWIW, the version number of the offending `sld` files is 0x42, `XcaliburVersion_2_2`...

**Comment by chambm** [comment]
Thanks for the patch. Could you make it a PR? Infortunately I don't think we have any tests for sld files so I'll probably accept it as-is.
