### ISSUE TITLE
Unable to locate package pwiz-setup-3.0.22298.76c82e9-x86_64.msi

### ISSUE THREAD

**Issue by annapurnap2007** [ProteoWizard/pwiz#2335]
I am very new to Ubuntu system and trying to install pwiz. It's giving the error attached. 
![image](https://user-images.githubusercontent.com/113557245/197820473-e2e49dfb-18c5-4a9f-86c0-43088c615327.png)
Appreciate any help with this issue.

**Comment by annapurnap2007** [comment]
Thanks Chambm! I downloaded Linux  non-vendor native builds and when tried to install, It's giving the error attached.
![Screenshot from 2022-10-25 12-58-10](https://user-images.githubusercontent.com/113557245/197847447-6cc27376-5647-4278-917a-0bef6e027c3a.png)

Please advice me on how to proceed further.

**Comment by chambm** [comment]
That's a tarball (*nix-style zip file). You don't install it with apt.
https://linuxize.com/post/how-to-extract-unzip-tar-gz-file/

**Comment by annapurnap2007** [comment]
Thank very much! File extracted, but I don't see any configure file in the list.
![Screenshot from 2022-10-25 13-54-48](https://user-images.githubusercontent.com/113557245/197858272-d260a0e8-d8ba-4c88-9167-845d6d22fef6.png)

**Comment by chambm** [comment]
What are you trying to do with ProteoWizard? All the binaries are there. msconvert, idconvert, msaccess, etc.

**Comment by annapurnap2007** [comment]
I have no idea. I downloaded pwiz-bin-linux-x86_64-gcc7-release-3_0_22298_120f8aa.tar.bz2 using option "Linux non-vendor native builds". After extracting, all these components listed.

**Comment by chambm** [comment]
Why are you installing/downloading ProteoWizard?

**Comment by annapurnap2007** [comment]
I would like to use MSconvert to convert LC-MS RAW files to mzML files. As I mentioned I am new to Linux system. Please advice me on how to proceed. Please share step by step protocol, if you have any.

**Comment by chambm** [comment]
You can't use the native non-vendor builds for **vendor** proprietary RAW files. You have to use the Docker image, or switch to Windows and do the conversions there. I highly recommend the Windows route since you seem more comfortable with GUI programs.

**Comment by annapurnap2007** [comment]
Thanks Chamber! It's working fine on Windows system.
