### ISSUE TITLE
Filter runs in msconvert

### ISSUE THREAD

**Issue by nx10** [ProteoWizard/pwiz#240]
Hello and first of all thank you for this amazing tool. The following question is regarding msconvert.exe:

I am trying to convert big (AB SCIEX) .WIFF files containing multiple thousands of single runs. I was wondering if there is any possibility to select or filter the run index as you can do with spectra/chromatograms. 

something like:

--runFilter "index 1-500"

Thank you for your time!

**Comment by chambm** [comment]
msconvert (command-line only) now supports --runIndexSet in the latest version.
