### ISSUE TITLE
Using the scan filter in proteowizard for thermo files, the mzML files contains no scans

### ISSUE THREAD

**Issue by michelleemoss** [ProteoWizard/pwiz#2408]
Used the MSConvert GUI version 3.0.22336 to generate an mzML of thermo file with the scan filter on. Then opened new mzML file into SeeMS and it contains no scans. 

![Screenshot 2022-12-05 105031](https://user-images.githubusercontent.com/119880095/205696364-6e856ca9-5004-48fb-a0e2-963e50e85327.png)

![Screenshot 2022-12-05 105013](https://user-images.githubusercontent.com/119880095/205696307-413827f3-6f9b-46fb-886c-a46eb0baa996.png)

**Comment by chambm** [comment]
Try the SIM as Spectra option.

**Comment by michelleemoss** [comment]
@chambm Just tried that and I'm seeing the same results

**Comment by michelleemoss** [comment]
@chambm Matt, here is a link to the thermo raw file in question. Thanks 
https://drive.google.com/drive/folders/1Vl9rybBRgieySclGiBgM4Piqy90A6BsD

**Comment by chambm** [comment]
What version of pwiz? I'm able to filter that file on scan numbers 5-10 with no issue.

**Comment by michelleemoss** [comment]
@chambm version 3.0.22336
