### ISSUE TITLE
subset feature fails to separate the assigned "Scan number"

### ISSUE THREAD

**Issue by sajfb** [ProteoWizard/pwiz#2460]
I have *.D* data files that can be easily converted into *.mzML* format; however, the subset feature cannot generate *.mzML* files only from the assigned scan number boundaries.

Here is a link to the data (*.D* format) from metabolomics workbench:

https://www.metabolomicsworkbench.org/data/DRCCStudySummary.php?Mode=SetupRawDataDownload&StudyID=ST001190

**Comment by sajfb** [comment]
Here is a link to the data (*.D* format) from metabolomics workbench:

https://www.metabolomicsworkbench.org/data/DRCCStudySummary.php?Mode=SetupRawDataDownload&StudyID=ST001190

**Comment by sajfb** [comment]
I tried using the **Scan time** boundaries to isolate the desired scans and it worked, but the *Scan number* can not work to isolate the desired scans.

**Comment by chambm** [comment]
Glad you got it working. Agilent does have scan numbers but they are not contiguous. Look at the .D or mzML file in SeeMS to see what they are.
