### ISSUE TITLE
Questions regarding the future of Docker

### ISSUE THREAD

**Issue by Esfo** [ProteoWizard/pwiz#2534]
It looks like docker is going to stop offering free service. I wanted to raise awareness in case it wasn't known and ask if this will affect the linux-docker availability of msconvert in the future?

**Comment by chambm** [comment]
It's only the free organization tier that may be going away. They're being pretty cagey about whether that means the entire team will go away (including public repositories), or just the private repositories. We have applied for their open source program. If we don't get accepted we will find another way either on Docker or another repository (like quay.io).

**Comment by Esfo** [comment]
glad you're on top of it, thank you for all your work

**Comment by chambm** [comment]
https://hub.docker.com/r/proteowizard/pwiz-skyline-i-agree-to-the-vendor-licenses

**Comment by edmondop** [comment]
Thanks, I understand the Dockerfile is stored within a separate repo, would it make sense to move it into this repo?

Anyways, I was trying to understand what base image this is using, but at least for me it seems that DockerHub ui is not working well or there are too many layers for the ui
