### ISSUE TITLE
Exceding maxium file path length limitation in msconvert

### ISSUE THREAD

**Issue by ajmaurais** [ProteoWizard/pwiz#2540]
I am trying to run msconvert using the proteowizard docker container inside of a wdl pipeline that I am running with cromwell. Cromwell creates large directory trees which can have path absolute file paths lengths longer than 250 characters. The msconvert task in my workflow is immediately failing and writes the following to the standard error stream:

```
Error writing run 1:
path is too long (must be 250 characters or less): Z:\cromwell-executions\DIA_Panorama_EncyclopeDIA\0a2e9e67-cc11-4f48-a472-6b66c87f26c0\call-get_ms_data_files\get_ms_data_files\e9be6200-4e6e-459a-84db-3fddf28fabb5\call-msconvert_subset\execution\.\CPTAC_CCRCC_W_JHU_20200710_LUMOS_CPT007730_ITH_02.mzML
```

I get the same error even when I modified my pipeline to give msconvert a relative path shorter than 250 characters instead of an absolute path.

I believe that msconvert is failing because of the exception raised by the `check_path_length` function.

https://github.com/ProteoWizard/pwiz/blob/4c5e3b2781d9254a62d6f43caf84925825a1c40b/pwiz/utility/misc/Filesystem.cpp#L719-L727

This function calculates the absolute file path regardless of whether it is given a relative or absolute file path. Is there a reason that the maximum path limit is checked using the absolute file path? Shouldn't this be done with the relative file path? 

Also, the body of `check_path_length` is only run when the `WIN32` macro is defined. Aren't we using the the 64 bit version of proteowizard in the docker container? Shouldn't there not even be a maxim path length limitation in the 64 bit version?

**Comment by chambm** [comment]
I think Windows path limits apply to the absolute path even when you have some paths in relative form. Ultimately a relative path has to resolve to an absolute path and the MAX_PATH applies at that point. We're just doing an early check to avoid hard to understand system errors. As I replied to you by email:

> From my Googling I don't see any way to fix this with Wine. The only thing I can think of is prefixing paths with \\\\?\\, but even if that worked in Wine (which I'm not sure of), that would almost certainly also require changes in Cromwell. So if you had to change Cromwell it would probably be easier to just make it use shorter paths.
