### ISSUE TITLE
Support for importing Sage search results

### ISSUE THREAD

**Issue by lazear** [ProteoWizard/pwiz#2584]
Hi,

Is it possible to add support for importing search results from [Sage](https://github.com/lazear/sage) into Skyline? It's a simple TSV based format, with some example rows below.

A couple notes (happy to provide more info if you decide to add support):

- filename may contain ".gz" at the end - Sage can directly search mzMLs packaged in gzip, as exported by MSConvert, etc.
- Peptide sequences follow the ProForma notation: N-terminal modifications are specified as "[+42.0]-PEPT[+57.0]IDE", and C-terminal as "PEPTIDE-[+42.0]", etc.
- Currently, Sage is outputting unfiltered results, so decoys will be present (`label = -1`), and uses a built-in PSM rescorer (with spectrum_fdr, peptide_fdr, protein_fdr  and "posterior_error" corresponding to log10(PEP) at the spectrum level)

|peptide                             |proteins                                  |num_proteins|filename                                                |scannr            |rank              |label     |expmass|calcmass |charge   |peptide_len|missed_cleavages|isotope_error|precursor_ppm|fragment_ppm|hyperscore        |delta_next                 |delta_best        |rt                |aligned_rt|predicted_rt|delta_rt_model   |matched_peaks|longest_b  |longest_y|longest_y_pct|matched_intensity_pct|scored_candidates|poisson            |sage_discriminant_score|posterior_error    |spectrum_fdr |peptide_fdr  |protein_fdr  |ms1_intensity|ms2_intensity|
|------------------------------------|------------------------------------------|------------|--------------------------------------------------------|------------------|------------------|----------|-------|---------|---------|-----------|----------------|-------------|-------------|------------|------------------|---------------------------|------------------|------------------|----------|------------|-----------------|-------------|-----------|---------|-------------|---------------------|-----------------|-------------------|-----------------------|-------------------|-------------|-------------|-------------|-------------|-------------|
|DKPDNFQLFQSPHGK                     |sp&#124;Cont_Q29443&#124;TRFE_BOVIN                 |1           |B03_05_150304_human_ecoli_E_3ul_3um_column_95_HCD_OT_2hrs_30B_9B.mzML.gz|controllerType=0 controllerNumber=1 scan=17496|1                 |1         |1756.853|1756.8533|2        |15         |0               |0.0          |0.13896473   |3.5193627   |34.19992755314387 |34.19992755314387          |0.0               |52.904984         |9.401352  |10.61555    |0.006991029      |12           |0          |12       |0.8          |38.772728            |212              |-9.181715169377561 |1.0735033              |-92.260376         |0.0000063835355|0.000084399624|0.0002882782 |1868499.0    |159085.38    |
|MTQNPNYYNLQGISHR                    |sp&#124;O75643&#124;U520_HUMAN                      |1           |B03_20_150304_human_ecoli_A_3ul_3um_column_95_HCD_OT_2hrs_30B_9B.mzML.gz|controllerType=0 controllerNumber=1 scan=18901|1                 |1         |1933.9033|1934.9059|2        |16         |0               |-1.00335     |0.40650183   |2.5280108   |34.25190054880667 |34.25190054880667          |0.0               |54.706657         |11.610434 |9.96067     |0.009498894      |12           |0          |9        |0.5625       |59.16637             |119              |-9.158327129100417 |1.073072               |-91.65352          |0.0000063835355|0.000084399624|0.0002882782 |706189.3     |167572.2     |
|IGPQQSISTSVGPSASQR                  |sp&#124;Q8WUD1&#124;RAB2B_HUMAN                     |1           |B03_11_150304_human_ecoli_A_3ul_3um_column_95_HCD_OT_2hrs_30B_9B.mzML.gz|controllerType=0 controllerNumber=1 scan=16600|1                 |1         |1798.9171|1798.9172|2        |18         |0               |0.0          |0.06785766   |3.965634    |34.609430061698184|12.066867819490565         |0.0               |50.22712          |6.7463007 |7.8116045   |0.006133735      |12           |0          |9        |0.5          |55.194157            |271              |-9.263529298677936 |1.0594196              |-81.609634         |0.0000063835355|0.000084399624|0.0002882782 |2615488.5    |239593.95    |
|LGSTAPQVLSTSSPAQQAENEAK             |sp&#124;Q9UNZ2&#124;NSF1C_HUMAN                     |1           |B03_11_150304_human_ecoli_A_3ul_3um_column_95_HCD_OT_2hrs_30B_9B.mzML.gz|controllerType=0 controllerNumber=1 scan=24964|1                 |1         |2313.1453|2313.1448|2        |23         |0               |0.0          |0.21108977   |4.9388676   |34.204749270921916|34.204749270921916         |0.0               |64.19331          |21.880896 |21.301785   |0.0033343732     |12           |0          |7        |0.3043478    |41.02911             |275              |-9.143498872552062 |1.0535635              |-77.37298          |0.0000063835355|0.000084399624|0.0002882782 |4221521.5    |159854.3     |
|IVNGWQVEEADDWLR                     |sp&#124;P11216&#124;PYGB_HUMAN                      |1           |B03_17_150304_human_ecoli_D_3ul_3um_column_95_HCD_OT_2hrs_30B_9B.mzML.gz|controllerType=0 controllerNumber=1 scan=60051|1                 |1         |1828.8752|1828.8745|2        |15         |0               |0.0          |0.40047675   |2.3272831   |46.064587055185285|46.064587055185285         |0.0               |122.00684         |84.44479  |84.930725   |0.002797842      |14           |1          |13       |0.8666667    |53.667305            |235              |-11.50757341461281 |1.0525995              |-76.89021          |0.0000063835355|0.000084399624|0.0002882782 |3275407.0    |286701.94    |
|TSPNEGLSGNPADLER                    |sp&#124;P20020&#124;AT2B1_HUMAN                     |1           |B03_09_150304_human_ecoli_B_3ul_3um_column_95_HCD_OT_2hrs_30B_9B.mzML.gz|controllerType=0 controllerNumber=1 scan=18590|1                 |1         |1655.7739|1655.7751|2        |16         |0               |0.0          |0.73723996   |1.8929093   |35.27861363014335 |35.27861363014335          |0.0               |54.692764         |11.06111  |13.715663   |0.01528421       |12           |0          |9        |0.5625       |61.4172              |237              |-9.210653530206312 |1.0498272              |-74.88978          |0.0000063835355|0.000084399624|0.0002882782 |3074109.0    |467842.28    |
|YSQTGNYELAVALSR                     |sp&#124;P39656&#124;OST48_HUMAN                     |1           |B03_07_150304_human_ecoli_D_3ul_3um_column_95_HCD_OT_2hrs_30B_9B.mzML.gz|controllerType=0 controllerNumber=1 scan=37747|1                 |1         |1670.8262|1670.8263|2        |15         |0               |0.0          |0.07305985   |3.3973744   |35.030795333974936|11.315976019656382         |0.0               |87.47773          |46.78585  |47.73015    |0.0054370165     |12           |0          |12       |0.8          |43.222576            |579              |-9.123503452694049 |1.0437266              |-70.77262          |0.0000063835355|0.000084399624|0.0002882782 |3417883.8    |365151.5     |
|LYGPTNFSPIINHVAR                    |sp&#124;O75131&#124;CPNE3_HUMAN                     |1           |B03_14_150304_human_ecoli_D_3ul_3um_column_95_HCD_OT_2hrs_30B_9B.mzML.gz|controllerType=0 controllerNumber=1 scan=40016|1                 |1         |1797.9524|1797.9526|2        |16         |0               |0.0          |0.13578814   |2.658183    |32.23010127037814 |32.23010127037814          |0.0               |88.955185         |48.919636 |44.31631    |0.026504695      |11           |0          |5        |0.3125       |59.419533            |295              |-8.29641112411362  |1.0431533              |-70.342926         |0.0000063835355|0.000084399624|0.0002882782 |2085699.8    |278289.12    |
|IVTGVTASQALLDEAVR                   |sp&#124;P0AFP6&#124;GCH1L_ECOLI                     |1           |B03_08_150304_human_ecoli_C_3ul_3um_column_95_HCD_OT_2hrs_30B_9B.mzML.gz|controllerType=0 controllerNumber=1 scan=50043|1                 |1         |1741.9575|1741.9574|2        |17         |0               |0.0          |0.07007652   |2.1040714   |36.10958188829575 |36.10958188829575          |0.0               |107.6134          |68.8282   |67.2472     |0.009103         |12           |0          |12       |0.7058824    |41.167507            |507              |-9.004576904410902 |1.0417991              |-69.4401           |0.0000063835355|0.000084399624|0.0002882782 |6260311.0    |1073952.1    |

**Comment by brendanx67** [comment]
Can you post this to the Skyline support board complete with a pointer to example files (posted to https://skyline.ms/files.url)?

We always try to support these requests as long as we have enough example data. We do now support an extensive set of pipelines (https://skyline.ms/build-blib.url).
