### ISSUE TITLE
Problems converting Waters. raw to .mzML

### ISSUE THREAD

**Issue by SivanXW** [ProteoWizard/pwiz#2595]
Hi, when I tried to covert my files (Waters. raw) obtained by q-Tof MS to .mzML files using msconvert (the newest version), errors occured:
  **Waters RAWreader not implemented: support was explicitly disabled when program was built **
When I used seeMS to open my files (Waters. raw), the same error appeared again. 
![image](https://github.com/ProteoWizard/pwiz/assets/108386199/2f6311c8-3b00-4c29-ad09-10ea222816b8)
However, this error didnot occur when opening the same file about 4 months ago. 

I'm wondering how to solve this problem, thanks!

**Comment by chambm** [comment]
Is it possible you downloaded the ProteoWizard archive built without vendor support? If not can you try downloading the latest version again and see if the problem still occurs?
