### ISSUE TITLE
How to use the pressure chromatogram feature by our end users

### ISSUE THREAD

**Issue by dingxuan1990** [ProteoWizard/pwiz#2670]
I have been using your marvelous software for a long time. Recently, I noticed that you have updated a support for pressure chromatogram of thermo raw files. This feature is exactly what I want and I really appreciate your work. 

But I did not find any related settings in the MSconvert GUI. Would you please show me how to use this feature to extract pressure information from thermo raw files?

Looking forward to your reply.

Yous,
Ding Xuan

**Comment by chambm** [comment]
You should just be able to open a RAW file in SeeMS and see the pressure chromatograms in the chromatogram list. Then if you convert the file to mzML the file will have those chromatograms as well if you need to import it to some other software.
