### ISSUE TITLE
MS2Denoise & MS2Deisotope

### ISSUE THREAD

**Issue by feng6544** [ProteoWizard/pwiz#2686]
1. If I want to use MSConvert's MS2Denoise and MS2Deisotope functions, how do I set them up in the MSConvertGUI.If I can't use this feature in the GUI, can you give me a default form for using both of these features on the command line？
2. "C:\mysoftware\MSConvertGUI\msconvert.exe" --zlib --filter "peakPicking vendor msLevel=1-" --filter "titleMaker <RunId>.<ScanNumber>.<ScanNumber>.<ChargeState> File:"""^<SourcePath^>""", NativeID:"""^<Id^>""""  "C:\Users\feng\Desktop\test.mgf"
When I convert mgf files to mzML, is this setting correct, and is peakPicking necessary？

**Comment by chambm** [comment]
`--filter "MS2Denoise"` and `--filter "MS2Deisotope"` will do the trick. You can see what options you can pass inside the quotation marks by referring to that tool's section:
https://proteowizard.sourceforge.io/tools/msconvert.html

MGF files should already peak picked, so the peak picking filter on them will take no action.
