### ISSUE TITLE
Bug: scan offset by +1 upon using the "--filter index" option

### ISSUE THREAD

**Issue by lgillet** [ProteoWizard/pwiz#2814]
Dear all, 

I am not sure if that has been reported yet. I think I encountered a bug while trying to export specific scan from a file. 

Here is the command I ran: 
msconvert.exe FILE.mzXML --mzXML --filter "index [79,79] [1136,1138]" --outfile FILE_mini.mzXML
=> this exported the scans 80 and 1137-1139 (i.e. offset by +1 compared to what I was requesting/expecting). 

I confirmed the bug upon exporting to mgf and by starting from the .raw instead of the .mzXML file as well. 

Nothing "too bad" (I have offset my requested scans by -1 and I got the scans I wanted as output). 
But maybe just something to be aware if you don't know/don't check the output files?

Hope that helps

Ludovic

**Comment by chambm** [comment]
Hi Ludovic,

The index is 0-based (the same as the one inside an mzML file). There is a scanNumber filter as well which is 1-based, but note that one only works for vendor formats that have a "scan=" value in their nativeIDs.

Hope this clears up the confusion.
