### ISSUE TITLE
mzMLb. Handling of non-standard binary arrays.

### ISSUE THREAD

**Issue by timosachsenberg** [ProteoWizard/pwiz#2838]
Thanks for adding mzMLb support!

I just tried the conversion with a small file and dumped the XML part of the mzMLb:
 
```
     <chromatogramList count="1" defaultDataProcessingRef="pwiz_Reader_Thermo_conversion">
1890:       <chromatogram index="0" id="TIC" defaultArrayLength="0">
1890:         <cvParam cvRef="MS" accession="MS:1000235" name="total ion current chromatogram" value=""/>
1890:         <binaryDataArrayList count="3">
1890:           <binaryDataArray encodedLength="0">
1890:             <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" value=""/>
1890:             <cvParam cvRef="MS" accession="MS:1000576" name="no compression" value=""/>
1890:             <cvParam cvRef="MS" accession="MS:1002841" name="external HDF5 dataset" value="chromatogram_MS_1000595_double"/>
1890:             <cvParam cvRef="MS" accession="MS:1002843" name="external array length" value="48"/>
1890:             <cvParam cvRef="MS" accession="MS:1002842" name="external offset" value="0"/>
1890:             <cvParam cvRef="MS" accession="MS:1000595" name="time array" value="" unitCvRef="UO" unitAccession="UO:0000031" unitName="minute"/>
1890:             <binary/>
1890:           </binaryDataArray>
...
1890:           </binaryDataArray>
1890:           <binaryDataArray arrayLength="0" encodedLength="0">
1890:             <cvParam cvRef="MS" accession="MS:1000522" name="64-bit integer" value=""/>
1890:             <cvParam cvRef="MS" accession="MS:1000576" name="no compression" value=""/>
1890:             <cvParam cvRef="MS" accession="MS:1002841" name="external HDF5 dataset" value=""/>
1890:             <cvParam cvRef="MS" accession="MS:1002843" name="external array length" value="48"/>
1890:             <cvParam cvRef="MS" accession="MS:1002842" name="external offset" value="768385995360"/>
1890:             <cvParam cvRef="MS" accession="MS:1000786" name="non-standard data array" value="ms level" unitCvRef="UO" unitAccession="UO:0000186" unitName="dimensionless unit"/>
1890:             <binary/>
1890:           </binaryDataArray>
1890:         </binaryDataArrayList>
1890:       </chromatogram>
1890:     </chromatogramList>
```

for reference: in the mzML we have
<details>
  <summary>Click me</summary>
```
<binaryDataArray arrayLength="48" encodedLength="512">
              <cvParam cvRef="MS" accession="MS:1000522" name="64-bit integer" value=""/>
              <cvParam cvRef="MS" accession="MS:1000576" name="no compression" value=""/>
              <cvParam cvRef="MS" accession="MS:1000786" name="non-standard data array" value="ms level" unitCvRef="UO" unitAccession="UO:0000186" unitName="dimensionless unit"/>
              <binary>AQAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAA</binary>
            </binaryDataArray>
          </binaryDataArrayList>
```
</details>

Is this expected? I kind of expected the binary array to be referenced through an "external HDF5 dataset"?

Best,
Timo

**Comment by timosachsenberg** [comment]
Another question. I just converted an Astral raw file.
Is it expected that the mzMLb is larger than the zlib compressed mzML?
![image](https://github.com/ProteoWizard/pwiz/assets/5803621/7429a6a1-6711-451a-b2f0-656e2ed147a6)

**Comment by chambm** [comment]
Hi Timo,

The non-standard array is kept in the binary section of mzMLb, but that external HDF5 dataset parameter isn't being used apparently. I thought my unit tests were ensuring that the integer data arrays were preserved with the mzML <-> mzMLb, but due to an oversight they were being ignored by the test. Oops! I'll work on getting those serialized properly.

As for RAW size, Astral profile data isn't nearly as filtered as Orbitrap profile data, so it benefits greatly from compression. They're not even compressing it properly in the Astral RAW files, so just zipping those files will get you good compression, unlike older instruments. All that is to say if you have the -z flag enabled for mzMLb you'll get much smaller files than the RAWs. If you don't, you'll get bigger files than the RAWs.

**Comment by timosachsenberg** [comment]
Thanks! That is what I would have expected - but I think the GUI does not take the zlib checkbox into account:
![image](https://github.com/ProteoWizard/pwiz/assets/5803621/1105b57f-c5b7-47d7-a4db-bdada896e87e)

If I enable zlib on the command line (thanks for the hint) I indeed get much smaller files (14gb GUI vs 4 gb command line).

**Comment by chambm** [comment]
Yes I see there's some handling in the CLI for mzMLb when zlib is enabled that isn't in MSConvertGUI. Thanks for the report, I will get that fixed as well.
