### ISSUE TITLE
Sciex Wiff2 files converted to MZML looses intensity

### ISSUE THREAD

**Issue by Cagakan31** [ProteoWizard/pwiz#2893]
Hello,
My name is Cagakan from SCIEX, UK support team.
One of our customer is asking:
"When converting the wiff2 files to mzml the peak areas and intensities are much lower than when looking at them in SCIEXOS."

It would be great if you have an answer for that,
Thanks for your time.
Best.
Cagakan

**Comment by chambm** [comment]
Is this customer Ms. Panzenboeck? I've responded to her emails about this issue recently.
