### ISSUE TITLE
`MSConvert` outputs wrong encoding for Waters raw files

### ISSUE THREAD

**Issue by t0mdavid-m** [ProteoWizard/pwiz#3186]
We are using `MSConvert` to convert Waters `raw` files to `mzML`. Unfortunately we have been experiencing issues with downstream processing. The issues seem to be caused by the encoding of the `mzML` files.

The `mzML` files are encoded with `Windows-1252` but in the header `UTF-8` is reported:
```
<?xml version="1.0" encoding="utf-8"?> 
```

This causes our XML-Parser to assume `UTF-8` and fail when running into non-ASCII characters (in our case `µ`/`b5` was problematic).

I would suggest to either convert the files to `UTF-8` or report the correct encoding in the header (I could not find any requirements for `UTF-8` in the `mzML` specification).

**Comment by chambm** [comment]
What element/attribute had the non-ASCII character? Filepaths should be UTF-8 encoded and XML ids and idrefs should be _xHHHH_ encoded.

**Comment by chambm** [comment]
Interesting. Looks like Visual C++'s isalpha() function says µ is an alphabetic character. But their example code implies it's not:

https://learn.microsoft.com/en-us/cpp/c-runtime-library/character-classification?view=msvc-170
> Generally these routines execute faster than tests you might write and should be favored over. For example, the following code executes slower than a call to isalpha(c):
> 
> if ((c >= 'A') && (c <= 'Z')) || ((c >= 'a') && (c <= 'z'))
>     return TRUE;

Looks like I need to go for the simpler approach.
