### ISSUE TITLE
Wine linux version

### ISSUE THREAD

**Issue by rsalz** [ProteoWizard/pwiz#331]
Hello! On your readme it says that there is a wine linux version (in a docker container?). I just spent half of today trying to get msconvert to work in a wine env in ubuntu so I'm very interested! How can I obtain it?

**Comment by chambm** [comment]
There's an older version here on DockerHub: https://hub.docker.com/r/chambm/pwiz-skyline-i-agree-to-the-vendor-licenses/

Eventually I'll be updating that one fairly frequently but for now you'll need to download the tarball and do `docker load` (maybe you can `docker load` from a URL, I'm not sure):
http://teamcity.labkey.org/guestAuth/repository/download/ProteoWizardAndSkylineDockerContainerWineX8664/lastSuccessful/pwiz-skyline-i-agree-to-the-vendor-licenses.tbz2

**Comment by soerendip** [comment]
Is there any description available on how to use the container?

**Comment by chambm** [comment]
The latest version with tips on how to run it is at: https://hub.docker.com/r/proteowizard/pwiz-skyline-i-agree-to-the-vendor-licenses/
