### ISSUE TITLE
MSConvert: SHA1 hashing excessive memory usage

### ISSUE THREAD

**Issue by austinkeller** [ProteoWizard/pwiz#352]
### Context
I came across this issue while processing large (>50Gb) mzML files for profile demultiplexing. Updating to a newer SHA1 library version, which does not include memory mapping, seemed to fix the problem.
See https://github.com/ProteoWizard/pwiz/pull/332#discussion_r237692326
However, we would like to keep the memory mapping functionality for it's speed benefits.

### Problem
File conversion of my large files failed after all of my physical memory would be consumed during the hashing step. The SHA1 implementation uses memory mapping to load the entire file into virtual memory, but this memory should be released as the file is hashed. This doesn't seem to be the case as all physical memory will be consumed if the file size is roughly greater than the available memory.

### Possible solution
Identify where memory is not being released and fix in the SHA1 library:
https://github.com/ProteoWizard/pwiz/blob/62eb002bed1f169cd1d3a73b9885bab31e7f4f69/pwiz/utility/misc/SHA1.cpp
https://github.com/ProteoWizard/pwiz/blob/62eb002bed1f169cd1d3a73b9885bab31e7f4f69/pwiz/utility/misc/SHA1.h

**Comment by chambm** [comment]
Fixed in #741 - finally! :)
