### ISSUE TITLE
Missing Precusor Mass when Converting Bruker TimsTOF to MZXML using pwiz

### ISSUE THREAD

**Issue by xuesu** [ProteoWizard/pwiz#355]
Dear sir,

I am using pwiz to extract TimsTOF signal from .d directory.

However, I found those signals lacking of precusor mass and charge. Just like this one:

![capture](https://user-images.githubusercontent.com/7857599/49503788-3366a700-f8b3-11e8-8aa9-687a6a2c358a.PNG)

I wonder that is because of pwiz or the file itself?

**Comment by chambm** [comment]
This is a peculiar trait of PASEF data. There can be MS2 scans with no precursor info. We initially chose to keep those scans, but later added a flag to exclude them. I don't think that flag has made it into msconvert or the GUI yet though. So you could probably filter them out with a wide isolation target filter like:
`--filter "precursorMz 0-10000"` (if I remember syntax right)

**Comment by xuesu** [comment]
Really? but when i used msconvert, it seems that all scans do not have precursor mass?

**Comment by chambm** [comment]
If you really have a PASEF file that msconvert converts without ANY precursor masses in the MS2 scans, I'd need to see it to understand what's going on.
