### ISSUE TITLE
License of the pwiz/utility/misc/pinned_gcroot.h file

### ISSUE THREAD

**Issue by lopippo** [ProteoWizard/pwiz#364]
Greetings,

currently packaging libpwiz for Debian, I would like to know what license governs the redistribution of the pwiz/utility/misc/pinned_gcroot.h file, apparently copyrighted to Microsoft. I need to list the various copyright holders of the files in the distribution for libpwiz to enter the Debian servers.

I wonder, however, if this file is needed at all in the GNU/Linux build environment ?

Thank you for your kind attention,
Sincerely
Filippo

**Comment by chambm** [comment]
Right, it's not needed for native Linux/OSX builds.

**Comment by lopippo** [comment]
Great, thanks, I'll close the issue.
Cheers,
Filippo
