### ISSUE TITLE
Creation of the autotools-based build starting from the bjam-based build system

### ISSUE THREAD

**Issue by lopippo** [ProteoWizard/pwiz#375]
Greetings,

I am currently working to streamline the autotools-based build of pwiz using the clever python-based "translation" of the bjam-based build log.

My experience is that the autotools-based build fails because the svm.h header is not found. I could fix that by modifying the python script file generate_autoconf.py to read like this:

		if ("libraries/boost_aux" in line) : # forward looking boostiness
			includes.add("libraries/boost_aux")
		if ("libraries/Eigen" in line) : #  make sure we ship Eigen and include it
			includes.add("libraries/Eigen")
		if ("libraries/CSpline" in line) : #  make sure we ship CSpline and include it
			includes.add("libraries/CSpline")
		if ("libraries/libsvm-3.0" in line) : #  make sure we ship libsvm-3.0 and include it
			includes.add("libraries/libsvm-3.0")

by addition of the the last two lines.

Then the build fails because BOOST_LDPATH is not defined, and the linker command line is erroneous:

/bin/sh ./libtool  --tag=CXX   --mode=link g++  -g -O2 -L -version-info 3:0:0 [.....]

which thus fails with the following error:

libtool:   error: require no space between '-L' and '-version-info'

Apparently, the boost.m4 file does not fill in that information bit. I tried looking into that boost.m4 file, but I found it cryptic...

Sincerely,
Filippo

**Comment by chambm** [comment]
Sorry, the autotools scripts are not officially supported. @bspratt originally created this but it hasn't been maintained recently. If you want to dig into it and fix it we're happy to take a PR to get it building again.

**Comment by lopippo** [comment]
I hope Brian is fine. I always had good and nice interaction with him in the past. I remember I did suggest some modifs. I'll work on it, then, as this is central to us.
Closing, then.
Cheers,
Filippo
