### ISSUE TITLE
Output mzML file violates schema/spec with empty chromatogram element for non-MS channel

### ISSUE THREAD

**Issue by chlige** [ProteoWizard/pwiz#429]
I am trying to convert a Thermo RAW file to mzML using msconvert.  When it converts the file it creates an “empty” chromatogram element, i.e. lacks binaryDataArrayList element, for the ECD channel in the data file.  This is causing issues trying to use the file in Mascot, as it violates the mzML schema.

Any help would be greatly appreciated.

Here is the snippet from the output mzML file.

```
      <chromatogramList count="2" defaultDataProcessingRef="pwiz_Reader_Thermo_conversion">
        <chromatogram index="0" id="TIC" defaultArrayLength="13209">
          <cvParam cvRef="MS" accession="MS:1000235" name="total ion current chromatogram" value=""/>
          <binaryDataArrayList count="2">
            <binaryDataArray encodedLength="105924">
...
          </binaryDataArrayList>
        </chromatogram>
        <chromatogram index="1" id="ECD" defaultArrayLength="0">
          <cvParam cvRef="MS" accession="MS:1000813" name="emission chromatogram" value=""/>
        </chromatogram>
      </chromatogramList>
```

**Comment by chambm** [comment]
Should be fixed in https://github.com/ProteoWizard/pwiz/pull/457 - thanks for the heads up.
