### ISSUE TITLE
tandem mass spec functions

### ISSUE THREAD

**Issue by michelleting** [ProteoWizard/pwiz#477]
Hi,
my lab has a waters triple quad instrument and I did a neutral loss scan that involves two functions (at two different collision energy), does the proteowizard MSConvert convert the two functions together in one mzml file? 
Thanks

**Comment by chambm** [comment]
Yes, all functions are written to the output file, including lockmass function if there is one. Each spectrum's id includes which function it originates from. The "preset scan configuration" CV param also corresponds to the function number.
