### ISSUE TITLE
[Reader_Thermo::fillInMetadata] unable to parse instrument model

### ISSUE THREAD

**Issue by sneumann** [ProteoWizard/pwiz#529]
Hi,
we're running a "GC (TraceGC Ultra, Thermo) - MS (SQ, Thermo) with Atlas Injector"
(see https://www.ipb-halle.de/en/research/cell-and-metabolic-biology/technical-resources/)
and get 
```
[Reader_Thermo::fillInMetadata] unable to parse instrument model; 
  please report this error to the ProteoWizard developers with this information: 
  model(ISQ Series) name(ISQ Series)
```
I guess this needs to be added somewhere near 
https://github.com/ProteoWizard/pwiz/blob/994311be06d0f0a969922fa513e6f5cfd49deb5c/pwiz_aux/msrc/utility/vendor_api/thermo/RawFileTypes.h#L168

but unsure if that simply requires to add
```
else if (type == "ISQ SERIES") return InstrumentModelType_ISQ;
```
If so, happy to send a PR.
Yours, Steffen

**Comment by chambm** [comment]
Hmm. I think the ISQ string is predicted so it could just be changed to "ISQ SERIES" in place of the current "ISQ". If anybody complains we can "ISQ" back. PR would be welcome!
