### ISSUE TITLE
msconvert outputs help into stderr

### ISSUE THREAD

**Issue by rita-gwen** [ProteoWizard/pwiz#543]
When I try to run `msconvert --help | less` on Ubuntu most of the output is not captured by the pipe. It works only when I do `msconvert --help 2> ~/msconvert.help`
Not a bit deal, of course, but is a bit awkward, especially with the amount of information it outputs.

**Comment by chambm** [comment]
It's by design so that output can be written to stdout without the status text intermingled (`-o -`).
