### ISSUE TITLE
MSConvert batch processing issue

### ISSUE THREAD

**Issue by saersamani** [ProteoWizard/pwiz#590]
Hi, 

When I run the latest version of MSConvert GUI on a Windows 7 64 bit on SWATH data, some of the scans remain empty with no recorded data. I do not have this issue when convert the files one at the time. Do you know what could cause such a problem?

Cheers,
Saer

**Comment by chambm** [comment]
Can you attach some screenshots demonstrating the problem? By "scan remain empty" do you mean an entire file, or just a few scans within the file?

**Comment by saersamani** [comment]
Please see two screenshots below. The first one shows the used 
parameters. and the second one shows the same files converted 
individually (folder called "mzXML_Files") and as a batch (folder called 
"Raw_Data_Pos"). As you can see the file "EA_001A" is completely empty 
in the batch mode and also the other files do not record all the scans.

**Comment by chambm** [comment]
I think you'll need to visit the GitHub issue directly to post attachments. The screenshots didn't come through.

**Comment by saersamani** [comment]
![cgdimjcgnbegmmgg](https://user-images.githubusercontent.com/29478548/63636165-19047180-c66c-11e9-9dba-c1bb4da3d6ca.png)
![pfhhpemhpokhobjk](https://user-images.githubusercontent.com/29478548/63636168-23bf0680-c66c-11e9-92e6-493c0fb063db.png)

Here are the screenshots.

**Comment by saersamani** [comment]
The first screenshot shows the parameter settings for the conversion. As you can see in that picture, none of those were checked. I will try again with “SIM as Spectra” and will let you know.

**Comment by saersamani** [comment]
Checking the SIM option solved the problem. Thanks for the help.

**Comment by sorenwacker** [comment]
How can I load multiple file in there?
