### ISSUE TITLE
boost::filesystem::create_directories: Invalid argument

### ISSUE THREAD

**Issue by aliyurtsevenn** [ProteoWizard/pwiz#811]
Hi, I have installed proteowizard from website and installed the tools by >sudo apt install libpwiz-tools. After I give  msconvert command in the working directory, I have got this error. Can you direct me what I should do to prevent this errorl. Thank you in advance.

a@a-Latitude-E5440:~/Downloads/pwiz$ msconvert P2-3_1.raw 
format: mzML 
    m/z: Compression-None, 64-bit
    intensity: Compression-None, 32-bit
    rt: Compression-None, 64-bit
ByteOrder_LittleEndian
 indexed="true"
outputPath: .
extension: .mzML
contactFilename: 

filters:
  
filenames:
  P2-3_1.raw
  
boost::filesystem::create_directories: Invalid argument
Please report this error to support@proteowizard.org.
Attach the command output and this version information in your report:

ProteoWizard release: 3.0.10827 (2017-5-11)
ProteoWizard MSData: 3.0.10827 (2017-5-11)
ProteoWizard Analysis: 3.0.10827 (2017-5-11)
Build date: Nov  1 2017 15:08:32

**Comment by chambm** [comment]
Download the latest version and try again. This error should be fixed. (always a good idea to download the latest version whenever you have a problem to see if it's fixed already).
