### ISSUE TITLE
MSConvertGUI.exe, build [Debug, x86] failed

### ISSUE THREAD

**Issue by IrisZheLi** [ProteoWizard/pwiz#901]
All the codes and settings are same as release. 
[Release, x86] build succeed, but [Debug, x86] failed.
CommonUtil.dll and CustomDataSourceDialog.dll are ok; but MSConvertGUI.exe failed.
Did I do soemthing wrong?
[MSConvertGUI_Build_DebugX86.docx](https://github.com/ProteoWizard/pwiz/files/4162194/MSConvertGUI_Build_DebugX86.docx)

**Comment by chambm** [comment]
Did you do a quickbuild with the debug flag added? Debug/release changes the C++ code drastically so it required a C++ recompile. Same with x86/x64 (that's address-model=32/64)

**Comment by IrisZheLi** [comment]
It wokrs; "quickbuild.bat address-model=64 variant=debug",
Thanks;
