### ISSUE TITLE
MSConvertGUI - Build [Debug, x64] succeed, but hangs up during running.

### ISSUE THREAD

**Issue by IrisZheLi** [ProteoWizard/pwiz#902]
[MSConvertGUI_Build_DebugX64.docx](https://github.com/ProteoWizard/pwiz/files/4162208/MSConvertGUI_Build_DebugX64.docx)

**Comment by chambm** [comment]
Try a full rebuild from Visual Studio after doing the full build with quickbuild. I'm not sure why it's required but it does seem to be necessary whenever refreshing the build from quickbuild.
