### ISSUE TITLE
MsConvert fillInMetadata unable to parse instrument TSQ Vantage AM

### ISSUE THREAD

**Issue by plpla** [ProteoWizard/pwiz#929]
I am trying to convert files from a TSQ Vantage instrument and I get this error:

`[Reader_Thermo::fillInMetadata] unable to parse instrument model; please report this error to the ProteoWizard developers with this information: model<TSQ Vantage AM> name<TSQ>;`

I will probably use the ignoreUnknownInstrumentError flag as suggested but it could be nice to have this handled properly.

**Comment by chambm** [comment]
Fixed in #938
